//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyParty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInfo
    {
        public int ClientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PostCode { get; set; }
        public string UnitNum { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
