//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDBwebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int VipLevel { get; set; }
    
        public virtual BillingInfo BillingInfo { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual PaymentInfo PaymentInfo { get; set; }
    }
}
