//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDBwebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecorationMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DecorationMenu()
        {
            this.DecorationArrangements = new HashSet<DecorationArrangement>();
        }
    
        public string DecorationId { get; set; }
        public string DecorationName { get; set; }
        public string Supplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecorationArrangement> DecorationArrangements { get; set; }
    }
}
