//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDBwebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string LocationId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> InviteeNum { get; set; }
        public Nullable<decimal> budget { get; set; }
    }
}
