//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDBwebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodArrangement
    {
        public int EventId { get; set; }
        public string FoodId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual FoodMenu FoodMenu { get; set; }
    }
}
