//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDBwebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string LocationId { get; set; }
        public string PostCode { get; set; }
        public string LocationAddress { get; set; }
        public string AdditionalInfo { get; set; }
    }
}
